### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by g4s8** [artipie/benchmarks#1]
Implement benchmarks tool set for Artipie repositories. Let's start with NPM registry.
These options has to be configured:
 - amount of download requests per time unit
 - amount of upload requests per time unit
 - TBD?

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) I'm not managing this repo, remove the [webhook](https://github.com/artipie/benchmarks/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/benchmarks` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `artipie/benchmarks` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by brastak** [comment]
> Implement benchmarks tool set for Artipie repositories. Let's start with NPM registry.
> These options has to be configured:
> 
> * amount of download requests per time unit
> * amount of upload requests per time unit
> * TBD?

@g4s8 It's hard to configure target throughput metrics. Usually, another approach is used. Test designer creates scenario with several roles doing some work. He specifies desired upload/download requests rate in the scenario conditions and run test with X users. After first run completed, test designer increase or decrease the number of simultaneous users and analyze impact for throughput. Please, see my PR, there is more detailed description here

**Comment by brastak** [comment]
@g4s8 Please, close this issue

**Comment by g4s8** [comment]
@brastak thanks

**Comment by 0crat** [comment]
I'm not managing `artipie/benchmarks` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)
