### ISSUE TITLE
Add benchmarks for files-adapter

### ISSUE THREAD

**Issue by brastak** [artipie/benchmarks#3]
Describe approach, scenarios and provide base results for artipie files adapter

**Comment by 0crat** [comment]
@brastak[/z](https://www.0crat.com/u/brastak) I'm not managing this repo, remove the [webhook](https://github.com/artipie/benchmarks/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/benchmarks` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `artipie/benchmarks` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)
