### ISSUE TITLE
Create a script to run benhmarks on AWS

### ISSUE THREAD

**Issue by g4s8** [artipie/benchmarks#4]
Create a script to:
 1. Start multiple EC2 instances with required configuration
 2. Deploy benchmarks targets to these instances
 3. Run benchmarks
 4. Download reports
 5. Destroy EC2 instances

Instances should be started in same region in one AWS subnet. We should use only instances ehich supports ENA:
https://aws.amazon.com/about-aws/whats-new/2016/06/introducing-elastic-network-adapter-ena-the-next-generation-network-interface-for-ec2-instances/ 
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking-ena.html

I think [Terraform](https://www.terraform.io/) is suitable for this, but feel free to discuss alternatives.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) I'm not managing this repo, remove the [webhook](https://github.com/artipie/benchmarks/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/benchmarks` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `artipie/benchmarks` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by brastak** [comment]
@g4s8 Please, close it

**Comment by 0crat** [comment]
I'm not managing `artipie/benchmarks` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)
